### ISSUE TITLE
waiting room bug: sqlite3. Recursive use of cursors not allowed.

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#184]
```
Traceback (most recent call last):
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask_socketio\__init__.py", line 44, in __call__
    start_response)
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\engineio\middleware.py", line 67, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documents\GitHub\labyrinth\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documents\GitHub\labyrinth\app\routes.py", line 26, in wrapped
    return f(*args, **kwargs)
  File "D:\Documents\GitHub\labyrinth\app\routes.py", line 242, in waiting_room
    return simple_render_template('rooms/waiting_room.html', room=db.rooms.get(room_id), maps=db.maps.get_all())
  File "D:\Documents\GitHub\labyrinth\database\room.py", line 50, in get
    self.cursor.execute('SELECT * FROM rooms WHERE id=?', [ID])
sqlite3.ProgrammingError: Recursive use of cursors not allowed.
```

**Comment by gtivansan** [comment]
[#165](https://github.com/m20-sch57/strategy-trial/issues/165)
