### ISSUE TITLE
Labyrinth: баг с бесконечным циклом и не только

### ISSUE THREAD

**Issue by lounres** [m20-sch57/labyrinth#198]
Я потестил, у меня игра не завершилась. А всё ругнулось на то, что игрок==`None`:

<details> <summary>Ошибка</summary>
<div class='highlight'><pre>
Traceback (most recent call last):
  File "D:\Documents\GitHub\labyrinth\labyrinth_test.py", line 54, in <module>
    msgs = TestLR.make_turn(input('(' + TestLR.get_active_player().get_username() + ') '))
  File "D:\Documents\GitHub\labyrinth\labyrinth_engine\labyrinth.py", line 133, in make_turn
    self.skip_turn()
  File "D:\Documents\GitHub\labyrinth\labyrinth_engine\labyrinth.py", line 159, in skip_turn
    obj.main()
  File "D:\Documents\GitHub\labyrinth\labyrinth_objects\Vanilla\empty.py", line 15, in main
    if next_active_player.get_parent() == self:
AttributeError: 'NoneType' object has no attribute 'get_parent'
</pre></div>
<div class='highlight'><pre>
{
    "seed": 3306429100453512403,
    "loadseed": 401554621664899169,
    "users": [
        "player #1",
        "player #2"
    ],
    "turns": [
        {
            "username": "player #1",
            "turn": "Идти вверх"
        },
        {
            "username": "player #2",
            "turn": "Идти вниз"
        },
        {
            "username": "player #1",
            "turn": "Подорвать справа"
        },
        {
            "username": "player #2",
            "turn": "Стрелять влево"
        },
        {
            "username": "player #1",
            "turn": ""
        },
        {
            "username": "player #2",
            "turn": "Стрелять влево"
        },
        {
            "username": "player #1",
            "turn": ""
        },
        {
            "username": "player #2",
            "turn": "Стрелять влево"
        },
        {
            "username": "player #2",
            "turn": ""
        },
        {
            "username": "player #2",
            "turn": "В яму"
        },
        {
            "username": "player #2",
            "turn": "Идти вправо"
        },
        {
            "username": "player #2",
            "turn": "Идти вправо"
        },
        {
            "username": "player #2",
            "turn": "Идти вверх"
        },
        {
            "username": "player #2",
            "turn": ""
        },
        {
            "username": "player #2",
            "turn": ""
        }
    ]
}
</pre></div>
</details>

А ещё я не очень понял: 

Вот есть настройка: заканчивать ли игру, когда все умерли.
Но если игру не закончить, то в теории лабиринт войдёт в цикл, что плохо.
Возможно нужно сделать настройку вида: 
`заканчивать через n ходов если ничего не случилось.`

**Comment by lounres** [comment]
Во время пропуска ходы ты запускаешь все `main`-функции. При этом в них нет проверки на то, что `игрок!=None`.

Думаю можно сделать декоратор `@is_turn`, чтобы функция не вызывалась, если `игрок == None`.
И в некоторых местах его применить. (Ясно, что не во всех. Где-то нужно будет прямо внутри написать `if player is not None`)

**Comment by lounres** [comment]
> Думаю можно сделать декоратор `@is_turn`, чтобы функция не вызывалась, если `игрок == None`.
> И в некоторых местах его применить. (Ясно, что не во всех. Где-то нужно будет прямо внутри написать `if player is not None`)

Мне кажется, это сложно. Проще будет просто прописать этот маленький if.
