### ISSUE TITLE
Удаление комнаты

### ISSUE THREAD

**Issue by MaxNacemit** [m20-sch57/labyrinth#92]
Надо добавить функционал кнопкам в комнате ожидания, у которых его нет.

**Comment by gtivansan** [comment]
Видимо нужно ещё удалять комнату, если в ней никого нет.

**Comment by MaxNacemit** [comment]
При попытке удалить комнату пишет вот это. 
![a3640484-0ec4-4055-b8c5-e5512add73b7](https://user-images.githubusercontent.com/43728459/53472136-e0e2f400-3a77-11e9-93be-fb07ba07fc09.png)

**Comment by MaxNacemit** [comment]
То был лог ошибок, лог сервера вот
![790ebe98-6d69-4832-bb40-2ebea05814d7](https://user-images.githubusercontent.com/43728459/53472203-0f60cf00-3a78-11e9-9e79-f79cd40cf0ac.png)

**Comment by MaxNacemit** [comment]
Алсо, кнопка «Покинуть комнату» стала работать дико тормознуто.

**Comment by gtivansan** [comment]
Всё что я могу сказать про ошибку - это то, что конкретно эта ошибка с удалением комнат никак не связанна. По какой-то неведомой мне причине клиент сделал запрос на адрес `"/game_rom/favicon.ico"` 


А кнопка единственное что тормозит?
Если нет, то скорее проблема в том, как ты запускаешь проект.
Если да, то у меня 0 идей, почему так происходит. (опять же на моём компе всё норм.)

**Comment by gtivansan** [comment]
А ещё, если я всё правильно понимаю, ты путаешь местами два действия:
- протестировать
- смёржить.

Нужно сначала тестировать и сообщать о проблемах, а потом уже мёржить.

**Comment by MaxNacemit** [comment]
Нажатие "Удалить комнату" вешает сайт хорошо и надежно. Комната в итоге не удаляется. Судя по логам, программа пытается писать что-то в закрытый вебсокет.

**Comment by MaxNacemit** [comment]
С компа "Покинуть комнату" работает еще более тормознуто.

**Comment by MaxNacemit** [comment]
"Начать игру" не работает вообще.

**Comment by MaxNacemit** [comment]
Все последние ошибки - одно и то же: ошибка записи в закрытый вебсокет.

**Comment by MaxNacemit** [comment]
Логи сервера говорят то же самое. 
![default](https://user-images.githubusercontent.com/43728459/53588298-a6737700-3b9d-11e9-9d42-0ae5b0bfc6fb.png)

**Comment by gtivansan** [comment]
1) запусти сервер без использования сторонних ресурсов (pythonanywhere)
2) Напиши что сказал сервер.
3) Напиши, что сказал клиент (F12 + вкладка console)

**Comment by gtivansan** [comment]
4. Лучше присылать не скрин, а скопированный текст.

**Comment by MaxNacemit** [comment]
Если так, то все работает. У тебя винда или линукс? Ни сервер, ни клиент не сказали ничего.

**Comment by MaxNacemit** [comment]
Нет, работает все-таки не все. При попытке сходить происходит это: 
Traceback (most recent call last):
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\developer\python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\developer\python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Кузьмин Максим\GitHub\labyrinth\app\routes.py", line 233, in game_room
    labyrinth.make_turn(turn)
  File "E:\Кузьмин Максим\GitHub\labyrinth\LabyrinthEngine\labyrinth.py", line 87, in make_turn
    self.save(self.filename)
  File "E:\Кузьмин Максим\GitHub\labyrinth\LabyrinthEngine\labyrinth.py", line 125, in save
    with open('tmp\\' + filename + '.save.json', 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\bolrpCIV.save.json'Traceback (most recent call last):
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\developer\python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\developer\python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\developer\python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Кузьмин Максим\GitHub\labyrinth\app\routes.py", line 233, in game_room
    labyrinth.make_turn(turn)
  File "E:\Кузьмин Максим\GitHub\labyrinth\LabyrinthEngine\labyrinth.py", line 87, in make_turn
    self.save(self.filename)
  File "E:\Кузьмин Максим\GitHub\labyrinth\LabyrinthEngine\labyrinth.py", line 125, in save
    with open('tmp\\' + filename + '.save.json', 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\bolrpCIV.save.json'

**Comment by gtivansan** [comment]
> У тебя винда или линукс?

винда

Ты случайно не удалил ли папку tmp?

**Comment by MaxNacemit** [comment]
Нет, я у себя ничего не удалял, только сделал fetch и ничего после этого не трогал

**Comment by gtivansan** [comment]
fetch?

Но сама папка tmp есть то?

**Comment by MaxNacemit** [comment]
Только что проверил - tmp на месте. 
На сервере линукс. Возможно, дело в этом. Предвидя вопрос: нет, туда нельзя поставить винду, и серверов с виндой не бывает в природе.
